# Generated by Django 5.0.4 on 2025-03-27 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_mission_commander'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronaut',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d+$')]),
        ),
    ]
