# Generated by Django 5.0.4 on 2025-03-23 12:19

import django.core.validators
import django.db.models.deletion
import main_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('birth_year', models.PositiveIntegerField(validators=[main_app.validators.NumberRangeValidator(1900, 2005, message='Value must be between 1900 and 2005')])),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Science', 'Science'), ('Education', 'Education')], default='Technology', max_length=10)),
                ('authors', models.ManyToManyField(related_name='articles', to='main_app.author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('rating', models.FloatField(validators=[main_app.validators.NumberRangeValidator(1.0, 5.0, message='Value must be between 1.0 and 5.0')])),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main_app.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main_app.author')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
