# Generated by Django 5.0.4 on 2025-02-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_artifact_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
