# Generated by Django 5.0.4 on 2025-02-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_menureview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menureview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='menureview',
            name='menu',
        ),
        migrations.AlterUniqueTogether(
            name='regularrestaurantreview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='regularrestaurantreview',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='FoodCriticRestaurantReview',
        ),
        migrations.DeleteModel(
            name='MenuReview',
        ),
        migrations.DeleteModel(
            name='RegularRestaurantReview',
        ),
    ]
