# Generated by Django 5.0.4 on 2025-03-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
