# Generated by Django 5.0.4 on 2025-03-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_quest_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon',
            name='wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
