# Generated by Django 5.0.4 on 2025-02-11 13:36

from django.db import migrations

def set_age_group(apps, schema_editor):
    persons_model = apps.get_model('main_app', 'Person')
    people = persons_model.objects.all()

    for person in people:
        if person.age <= 12:
            person.age_group = "Child"
        elif 13 <= person.age <= 18:
            person.age_group = "Teen"
        else:
            person.age_group = "Adult"

    persons_model.objects.bulk_update(people, ['age_group'])

def set_age_group_to_default(apps, schema_editor):
    persons_model = apps.get_model('main_app', 'Person')
    people = persons_model.objects.all()

    for person in people:
        person.age_group = "No age group"

    persons_model.objects.bulk_update(people, ['age_group'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group, set_age_group_to_default),
    ]
