# Generated by Django 5.0.4 on 2025-02-11 15:55

from django.db import migrations
from django.utils import timezone


def set_update_order_info(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')

    for order_model in order_model.objects.all():
        if order_model.status == "Pending":
            order_model.delivery = order_model.order_date + timezone.timedelta(days=3)
            order_model.save()
        elif order_model.status == "Completed":
            order_model.warranty = "24 months"
            order_model.save()
        elif order_model.status == "Cancelled":
            order_model.delete()

def reverse_update_order_info(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')

    for order_model in order_model.objects.all():
        if order_model.status == "Pending":
            order_model.delivery = None
        elif order_model.status == "Completed":
            order_model.warranty = order_model._meta.get_field('warranty').default

        order_model.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(set_update_order_info, reverse_update_order_info),
    ]
